In [ ]:
1. What is a Python library? Why do we use Python libraries?
A Python library is a collection of pre-written code and functionalities 
that can be imported and used in Python scripts or programs

In [ ]:
2. What is the difference between Numpy array and List?
 NumPy arrays and lists are both used to store collections of items
1. homogeneity: numpy array  stores all the same data type but list can contain
different data types
2. performance: numpy array better performance in numerical operations 
list are more flexible but may be slower in certain operations
3.size and dimension: numpy array support multidimensional arrays but lists are 
one dimension
4. functionality: numpy provides a variety of functions for numerical operations 
list are more general purpose and provide a wide range of methods for adding, 
removing or modifying items.


In [18]:
'''3. Fin dthe shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
print("shape of array",arr.shape)
print("dimenstion of array",arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of array (3, 4)
dimenstion of array 2


In [19]:
'''4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr[0]

array([1, 2, 3, 4])

In [21]:
'''5. How do you access the element at the third row and fourth column 
from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr[2][3]

12

In [27]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr[arr%2==1]


array([ 1,  3,  5,  7,  9, 11])

In [37]:
'''7. How can you generate a random 3x3 matrix with values between 0 and 1?'''
x=np.random.random((3,3))
print(x)

[[0.23467859 0.0437642  0.26613093]
 [0.89860105 0.09827803 0.21042308]
 [0.87305346 0.16058033 0.42960643]]


In [56]:
# 8. Describe the difference between np.random.rand and np.random.randn?
'''np.random.rand generates random numbers from a uniform distribution over the
interval [0,1)
np.random.randn generates random numbers from a normal distribution '''
rand_array = np.random.rand(2, 3)

In [38]:
'''9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [39]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [48]:
'''11. Consi^er the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1. Index wise multiplication
2. Matix multiplication
3. Add both the matices
4.Subtact matix B from A 
5.Divide Matix B by A'''
A=np.array([[1, 2, 3], [5, 6, 7],[9, 10, 11]])
B=np.array([[1, 2, 3], [5, 6, 7],[9, 10, 11]])
print("index wise\n",A*B)

index wise
 [[  1   4   9]
 [ 25  36  49]
 [ 81 100 121]]


In [50]:
print("Matrix mulitpication\n",A@B)

Matrix mulitpication
 [[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]


In [51]:
print("Matrix addition\n",A+B)

Matrix addition
 [[ 2  4  6]
 [10 12 14]
 [18 20 22]]


In [52]:
print("Subtact matix B from A\n",A-B)

Subtact matix B from A
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [53]:
print("Divison matrix\n",B/A)

Divison matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
arr.newbyteorder()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [ ]:
#13. What is the significance of the np.linalg.inv function?
The np.linalg.inv function in NumPy is used to compute the multiplicative 
inverse of a matrix.
The significance of the np.linalg.inv function lies in its applications, 
such as solving linear systems of equations, finding determinants, and 
inverting matrices, which are common tasks in linear algebra and numerical 
computations. 


In [ ]:
#15. What is broa^casting in Numpy?
Broadcasting in NumPy to perform operations on arrays of different shapes 
and sizes. In cases where the shapes of the arrays are not the same, 
NumPy automatically broadcasts the smaller array to make it compatible 
with the larger array, enabling element-wise operations without the need 
for explicit loop structures.


In [ ]:
#14. What soes the np.reshape function do, and how is it used?
The np.reshape function in NumPy is used to change the shape of an array
without changing its data. It allows you to rearrange the elements of an 
array to a new shape while maintaining the same total number of elements.